azs:
- name: z1
  cloud_properties: {zone: asia-east1-a}

vm_types:
- name: default
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
- name: g1-small
  cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
- name: g1-small-disk-50g
  cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
- name: n1-standard-1
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
- name: n1-standard-1-disk-50g
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
- name: n1-standard-2
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
- name: n1-standard-2-disk-50g
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
- name: disk-50g
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
- name: backend
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
    backend_service: concourse-gcp-backend

vm_extensions:
- name: concourse
  cloud_properties:
    elbs: pcf-router

disk_types:
- name: default
  disk_size: 3000

networks:
- name: default
  type: manual
  subnets:
  - range:   10.0.0.0/24
    gateway: 10.0.0.1
    dns:     [8.8.8.8, 8.8.4.4]
    azs:     [z1]
    reserved: [10.0.0.1, 10.0.0.2, 10.0.0.3]
    cloud_properties:
      network_name: bosh
      subnetwork_name: bosh-asia-east1
      ephemeral_external_ip: false 
      tags: [internal, concourse,http-server,https-server]
- name: vip
  type: vip

compilation:
  workers: 3
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
